name: Release Novo Elements
on: [workflow_dispatch]

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.BH_GIT_TOKEN }}
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.3
      - name: Install Dependencies
        run: |
          npm ci
      - name: Update Version Number
        run: |
          npm run version:elements
          git push --follow-tags origin master
      - name: Build
        run: |
          npm run build:ci
      - name: Publish Novo Elements
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/novo-elements/package.json
      - name: Publish Chomsky
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/chomsky/package.json